
title: Fun Size Hikes
baseurl: ""
url: "https://funsizehikes.com"

permalink: /:categories/:title:output_ext

paginate: 10
paginate_path: "/blog/page:num/"

plugins:
 - jekyll-paginate
 
defaults:
 - scope:
    path: "images/banners"
   values:
    bannerimg: true
       
author:
  - name: Eloise Robbins
  - email: eloise@funsizehikes.com
  - url: "https://funsizehikes.com"
 
# Leave off the development files and any other cruft so it doesn't go into the page
exclude:
  - Vagrantfile
  - dbgchrome.sh
  - gcloud.sh
  - setupruby.sh
  - CNAME
  - README.md
  - wordcloudwords.txt
